### ISSUE TITLE
Add instructions/links to files for users to run demo simulations

### ISSUE THREAD

**Issue by dbruneau-mie** [KVSlab/VaSP#104]
Currently, there are two additional files needed to run the offset stenosis (also the case for other simulations):
-mesh/file_stenosis_probe_point.json
-mesh/file_stenosis.h5
Eventually, we should write instructions in the Readme to show users where to obtain these files, or describe how users can make their own.

**Comment by keiyamamo** [comment]
HI @dbruneau-mie , Thanks for the feedback. I’m aware of the situation, but don’t know if I should set up zenodo right now or after the repository becomes ready since zenodo seems to be more for permanent storage. I’m consulting with @jorgensd  and find a way to share the mesh even before the repository  becomes fully functional.
